repos:
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.9
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.4
        hooks:
        - id: flake8
    -   repo: https://github.com/PyCQA/isort
        rev: 5.6.4
        hooks:
        - id: isort
    -   repo: local
        hooks:
        -   id: tests
            name: run tests
            entry: pytest -v
            language: system
            types: [python]
            stages: [push]

        